
sass:
    sass_dir: _sass

# baseurl can be used to automaticlaly prepend any links with, for example, a subdirectory
baseurl: ""

url: 
donate:
    page: https://secure.givelively.org/donate/bit-by-bit-coding
contact:
    email: info@bitbybitcoding.org
social:
    facebook: https://facebook.com/HelloWorldCodeCamp/
    instagram: https://instagram.com/_bitxbit_/



include:
 - scripts
 - .htaccess
 - imgs
 - styles
 - .well-known

url: "bitbybitcoding.org"
plugins:
  - jekyll-sitemap

defaults:
  -
    scope:
      path:            "archives/**/*"
    values:
      sitemap:         false