
sass:
    sass_dir: _sass

# baseurl can be used to automatically prepend any links with, for example, a subdirectory
baseurl: ""

url: 
donate:
    page: https://secure.givelively.org/donate/bit-by-bit-coding
contact:
    email: info@bitbybitcoding.org
social:
    facebook: https://www.facebook.com/BitByBitCoding
    instagram: https://instagram.com/_bitxbit_/
    linkedin: https://www.linkedin.com/company/bit-by-bit-coding/
financials:
    budget: https://drive.google.com/drive/folders/1xbxqDE_YCHFtpLDj_trKNevGDihlN00x?usp=sharing



include:
 - scripts
 - .htaccess
 - imgs
 - styles
 - .well-known

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from