
sass:
    sass_dir: _sass

# baseurl can be used to automatically prepend any links with, for example, a subdirectory
baseurl: ""

url: 
donate:
    page: https://secure.givelively.org/donate/bit-by-bit-coding
contact:
    email: info@bitbybitcoding.org
social:
    facebook: https://facebook.com/HelloWorldCodeCamp/
    instagram: https://instagram.com/_bitxbit_/
financials:
    budget: https://docs.google.com/spreadsheets/d/1eL4uR_xVK_c1v2oHe6p-3zlQ1R7OJ-hQOWASLtNdWoY/edit?usp=sharing



include:
 - scripts
 - .htaccess
 - imgs
 - styles
 - .well-known

plugins:
  - jekyll-sitemap