menu:
  - {name: Home, url: "/"}
  - name: Programs
    submenu:
      - name: Summer
        url: "#"
        subsubmenu:
          - {name: Uncommon Sense, url: "uncommonsenseseminar"}
          # - {name: Hello World, url: "helloworld"}
          - {name: Momentum, url: "momentum"}
          # - {name: Neural Logical, url: "neurallogical"}
      - name: School Year
        url: "#"
        subsubmenu:
          #- {name: Uncommon Sense, url: "uncommonsense"}
          - {name: Form & Function, url: "formfunction"}
  # - {name: Competition, url: "competition"}
  - name: About
    submenu:
      - {name: About Us, url: "aboutus"}
      - {name: Our Team, url: "ourteam"}
  - {name: Resources, url: "resources"}
  - {name: Volunteer, url: "volunteer"}
  - {name: Donate, url: "donate"}
